### ISSUE TITLE
Problem cropping some datasets

### ISSUE THREAD

**Issue by din14970** [din14970/TVIPSconverter#9]
Jiwon encountered the following issue on his dataset:

![image](https://user-images.githubusercontent.com/25320842/99788002-c476cd00-2b20-11eb-90e1-1e89a5044a4b.png)

![image](https://user-images.githubusercontent.com/25320842/99788043-d35d7f80-2b20-11eb-9030-9af7cfd476b2.png)

![image](https://user-images.githubusercontent.com/25320842/99788071-de181480-2b20-11eb-98fd-28d173f5c9d2.png)

My suspicion is that this is an EM-Conos dataset with snake-scan and a correction with hysteresis, which might be interacting with the cropping.

**Comment by harripj** [comment]
Hmm that's an interesting problem. I haven't tested on any data with hysteresis or snakescan as I don't have any unfortunately. The indices look correct for the crop but it looks like the full dataset is trying to be exported still. Did this error come up on export to .blo or .hspy?

**Comment by harripj** [comment]
I'm just trying this now, seems to work all okay for .hspy export, but not .blo

**Comment by harripj** [comment]
@din14970 I just took a look and my files will export in both .hspy and .blo with and without both hysteresis and snakescan after the updates. Would you be able to test on the dataset you mentioned here?

**Comment by din14970** [comment]
@harripj wow super fast fix, awesome! I don't have the dataset, I will have to ask Jiwon. I will quickly check it out, merge master and then release an update to pypi, it will be too much to ask Jiwon to install the dev version.

**Comment by harripj** [comment]
Okay! Hopefully it will do the trick, if not we will have to dig into it a bit further.

**Comment by din14970** [comment]
Seems to work on my datasets, although I initially had some issue with updating the VBF preview to use hysteresis and winding scan + cropped region. Not sure what caused it as I can't reproduce it now for some reason, and I'm not sure whether the output data was affected. Additionally, I found a couple minor issues/improvements which I will post in separate issues. For now I will update changelog, merge into master and make a new release.

**Comment by harripj** [comment]
Yes it seems to work for me too, and I had the initial problem you mentioned as well but also not able to reproduce. Curious.
